name: npm publish  # 定义工作流名称

on:
  workflow_dispatch:  # 允许手动触发工作流
  push:
    tags:
      - 'v*.*.*'  # 监听所有以 v 开头的标签，比如 v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest  # 指定运行环境为最新的 Ubuntu 版本
    steps:
      - uses: actions/checkout@v4  # 检出最新代码
      - uses: actions/setup-node@v4  # 设置 Node.js 环境
        with:
          node-version: 20  # 使用 Node.js 20 版本
      - run: pnpm i  # 安装项目依赖
      - run: npm test  # 运行测试

  # publish-npm:
  #   needs: build  # 依赖 build 作业，确保在 build 成功后再执行
  #   runs-on: ubuntu-latest  # 指定运行环境为最新的 Ubuntu 版本
  #   steps:
  #     - uses: actions/checkout@v4  # 检出最新代码
  #     - uses: actions/setup-node@v4  # 设置 Node.js 环境
  #       with:
  #         node-version: 20  # 使用 Node.js 20 版本
  #         registry-url: https://registry.npmjs.org/  # 配置 NPM 注册表 URL
  #     - run: npm ci  # 安装项目依赖
  #     - run: npm version ${{ github.ref_name }} --no-git-tag-version  # 使用推送的标签作为版本号，并防止创建新的 Git 标签
  #     - run: npm publish  # 发布包到 NPM 注册表
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # 使用 GitHub Secrets 中配置的 NPM 认证 token
